# Generated by Django 4.1.6 on 2025-05-04 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('hora_creacion', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Existe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ganar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestionar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('foto_portada', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marco_foto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nominacion',
            fields=[
                ('idNominacion', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('foto_perfil', models.TextField(blank=True)),
                ('foto_portada', models.TextField(blank=True)),
                ('biografia', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pertenecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Poseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Postular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('hora_creacion', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numCuenta', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El número de cuenta debe tener entre 1 y 9 dígitos', regex='^\\d{1,9}$')])),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('correoE', models.EmailField(max_length=100, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=12)),
                ('esAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tener',
            fields=[
                ('numCuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Votar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnoVotado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='app.usuario')),
                ('idNominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nominacion')),
                ('numCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to='app.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(check=models.Q(('numCuenta__gte', 1), ('numCuenta__lte', 999999999)), name='ck_usuario_numCuenta_range'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(check=models.Q(('correoE__regex', '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')), name='ck_usuario_correoE_format'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='numCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='postular',
            name='idNominacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nominacion'),
        ),
        migrations.AddField(
            model_name='postular',
            name='numCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='poseer',
            name='idComentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comentario'),
        ),
        migrations.AddField(
            model_name='poseer',
            name='idPublicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publicacion'),
        ),
        migrations.AddField(
            model_name='pertenecer',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupo'),
        ),
        migrations.AddField(
            model_name='pertenecer',
            name='numCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='marcofoto',
            name='idPerfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
        ),
        migrations.AddField(
            model_name='gestionar',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupo'),
        ),
        migrations.AddField(
            model_name='gestionar',
            name='numCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='ganar',
            name='idNominacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nominacion'),
        ),
        migrations.AddField(
            model_name='ganar',
            name='numCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='existe',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grupo'),
        ),
        migrations.AddField(
            model_name='existe',
            name='idNominacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nominacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='idPerfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='numCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='votar',
            unique_together={('numCuenta', 'idNominacion', 'alumnoVotado')},
        ),
        migrations.AddField(
            model_name='tener',
            name='idPerfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='postular',
            unique_together={('numCuenta', 'idNominacion')},
        ),
        migrations.AlterUniqueTogether(
            name='poseer',
            unique_together={('idComentario', 'idPublicacion')},
        ),
        migrations.AlterUniqueTogether(
            name='pertenecer',
            unique_together={('numCuenta', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='marcofoto',
            unique_together={('idPerfil', 'marco_foto')},
        ),
        migrations.AlterUniqueTogether(
            name='gestionar',
            unique_together={('numCuenta', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='ganar',
            unique_together={('idNominacion', 'numCuenta')},
        ),
        migrations.AlterUniqueTogether(
            name='existe',
            unique_together={('idNominacion', 'codigo')},
        ),
    ]
