# Generated by Django 4.1.6 on 2025-05-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('idMarco', models.AutoField(primary_key=True, serialize=False)),
                ('marco', models.ImageField(blank=True, upload_to='marco/')),
            ],
        ),
        migrations.AlterField(
            model_name='ganar',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marco'),
        ),
        migrations.AlterField(
            model_name='marcofoto',
            name='marco_foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marco'),
        ),
    ]
