# Generated by Django 4.1.6 on 2025-05-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
