# Generated by Django 4.1.6 on 2025-05-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pertenecer',
            options={'verbose_name': 'Pertenecer', 'verbose_name_plural': 'Pertenecer'},
        ),
    ]
