# Generated by Django 4.1.6 on 2025-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_portada',
            field=models.ImageField(blank=True, upload_to='portada/'),
        ),
    ]
