# Generated by Django 4.1.6 on 2025-05-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_perfil_foto_perfil_alter_perfil_foto_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='foto_portada',
            field=models.ImageField(blank=True, upload_to='grupos/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='publicacion/'),
        ),
    ]
