# Generated by Django 4.1.6 on 2025-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pertenecer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestionar',
            options={'verbose_name': 'Gestionar', 'verbose_name_plural': 'Gestionar'},
        ),
        migrations.AddField(
            model_name='grupo',
            name='codigo_acceso',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
