# Generated by Django 4.1.6 on 2025-05-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_marco_alter_ganar_premio_alter_marcofoto_marco_foto'),
        ('app', '0003_alter_gestionar_options_grupo_codigo_acceso'),
    ]

    operations = [
    ]
