# Generated by Django 4.1.6 on 2025-05-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20250520_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='codigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.grupo'),
            preserve_default=False,
        ),
    ]
