# Generated by Django 4.1.6 on 2025-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_publicacion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominacion',
            name='mostrar_resultados',
            field=models.BooleanField(default=True),
        ),
    ]
