# Generated by Django 4.1.6 on 2025-05-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20250525_1550'),
        ('app', '0006_nominacion_mostrar_resultados'),
    ]

    operations = [
    ]
