# Generated by Django 4.1.6 on 2025-05-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20250525_1637'),
        ('app', '0007_merge_20250525_1716'),
    ]

    operations = [
    ]
