# Generated by Django 4.1.6 on 2025-06-01 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20250525_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='marco',
            name='es_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marcofoto',
            name='idPerfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.perfil'),
        ),
    ]
