# Generated by Django 4.1.6 on 2025-06-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_marco_es_multiple_alter_marcofoto_idperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominacion',
            name='premio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.marco'),
            preserve_default=False,
        ),
    ]
