channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - branca=0.6.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - folium=0.14.0
  - idna=3.7
  - jinja2=3.1.5
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libopenblas=0.3.21
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=3.0.2
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=1.1.1w
  - pysocks=1.7.1
  - python=3.10.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pillow
  - pip:
      - django==4.1.6
      - django-crispy-forms==1.14.0
      - django-environ==0.9.0
      - django-pgtrigger==4.15.2
      - pip==25.1.1
      - psycopg2-binary==2.9.10
      - django-widget-tweaks
